sudo: required
notifications: never

addons:
  apt:
    sources:
    - sourceline: 'ppa:swi-prolog/stable'

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y swi-prolog

script:
  - echo "custom_run_tests." | swipl -s unittest.pro
